app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :students
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "projects#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/app/models/project.rb
class Project < ApplicationRecord
  has_many :students
end

app/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :project
end

app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
    respond_to do |format|
    format.html
    format.json { render json: @projects }
    format.xml { render xml: @projects }
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :url)
    end
end

app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_project

  def create
    @student = @project.students.new(student_params)
    
    respond_to do |format|
      if @student.save
        format.html { redirect_to @project, notice: 'Student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def student_params
    params.require(:student).permit(:studentid, :name)
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/projects_helper.rb
module ProjectsHelper
end

app/app/helpers/students_helper.rb
module StudentsHelper
end

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Students" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <% if user_signed_in? %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    <% end %>

  </body>
</html>

app/app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= project.url %>
  </p>

  <p>
    <strong>Students:</strong> 
    <% project.students.each do |student| %>
      <%= print student.name %>
    <% end %>
  </p>

  <p> 
    <strong>Students: </strong>
    <%= project.students.map{|student| student.name}.join(',') %>
    <strong> Total (
    <%= project.students.size %> )
    </strong> 
  </p>
</div>

app/app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/app/views/projects/show.html.erb
<h2>Students</h2>
<table>
  <thead>
    <tr>
      <th>Student ID</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @project.students.each do |student| %>
      <tr>
        <td><%= student.studentid %></td>
        <td><%= student.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<h2>Add a student:</h2>
<%= form_for([@project, @project.students.build]) do |f| %>
  <div class="field">
    <%= f.label :studentid %><br />
    <%= f.text_field :studentid %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br/>